services:
  - type: web
    name: borsa-analiz
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Ai__ApiKey
        sync: false
